"""Route 4 of "Make the recipes themselves better" — the floor under route 1.

Emily chose routes 1 then 4 on 2026-09-10, and chose what a failed check
should do: "tell you in the morning report." So these checks do two things —
notice, and be seen. A check writing to a log on a server nobody reads was on
the list of options and was not the one she picked.

Every fixture below is real. The two failing dinners and the passing one are
rows from the household database that motivated the ticket, generated by this
app before any of this existed:

  "Cottage Cheese with Pineapple-Free Fruit Cup" — both planner prompts
      forbid naming a dish after what it leaves out, in those words, using
      that exact example. It shipped anyway, and nothing looked.
  "Baked Lemon Herb Salmon with Roasted Asparagus" — sheet pan, drizzle,
      bake. Nothing browned, bloomed or layered.
  "Chicken Tikka Masala" — marinate, sear, sweat, bloom, simmer, finish.
      The control: it must stay clean, or the floor is just noise.
"""

import subprocess
import sys
from pathlib import Path

import pytest

from app import tools
from app.tools import plan_quality as q


REPO = Path(__file__).resolve().parent.parent

FOOD_RULES = {"dish_named_for_an_absence", "seasoning_never_mentioned", "method_is_assembly"}


def _dinner(date, name, steps, **extra):
    e = {"date": date, "slot": "dinner", "state": "planned", "meal_name": name,
         "instructions": steps}
    e.update(extra)
    return e


PINEAPPLE_FREE = _dinner("2026-09-07", "Cottage Cheese with Pineapple-Free Fruit Cup", [
    "Scoop cottage cheese into a bowl.",
    "Top with the fruit.",
    "Serve.",
])

SALMON = _dinner("2026-09-08", "Baked Lemon Herb Salmon with Roasted Asparagus", [
    "Preheat oven to 400F.",
    "Place salmon and trimmed asparagus on a sheet pan.",
    "Drizzle with olive oil, minced garlic, lemon juice, salt, and pepper.",
    "Top salmon with fresh dill and lemon slices.",
    "Bake for 12-15 minutes until salmon flakes easily.",
])

TIKKA = _dinner("2026-09-09", "Chicken Tikka Masala", [
    "Marinate chicken thighs in yogurt, half the garam masala, cumin, coriander, "
    "and turmeric for at least 1 hour (overnight is best).",
    "Sear marinated chicken pieces in a hot pan until browned, then set aside.",
    "In the same pan, saute diced onion, garlic, and ginger until soft.",
    "Add remaining spices and cook 1 minute until fragrant.",
    "Add crushed tomatoes and simmer 10 minutes.",
    "Stir in cream and return chicken to the pan; simmer until cooked through.",
    "Serve over basmati rice, garnished with cilantro.",
])


# What the household that produced these rows actually avoids — the fact
# "Emily is allergic to pineapple", flagged hard, is the one that makes
# "Pineapple-Free Fruit Cup" a violation rather than just an odd name.
AVOIDS = {"avoided": ["Emily is allergic to pineapple", "shellfish"]}


def _food_rules_fired(week, context=None):
    ctx = AVOIDS if context is None else context
    return {v.rule for v in q.check_week(week, ctx) if v.rule in FOOD_RULES}


# --------------------------------------------------------------------------
# The checks
# --------------------------------------------------------------------------

def test_a_dish_named_for_what_it_leaves_out_is_caught():
    """The rule was already written in both planner prompts. Nothing verified
    it, and this exact dish reached a real household's week."""
    assert "dish_named_for_an_absence" in _food_rules_fired([PINEAPPLE_FREE])


def test_assembly_masquerading_as_a_recipe_is_caught():
    """The salmon seasons itself (salt, garlic, lemon all appear), so the
    seasoning check correctly passes it. What it never does is cook: nothing
    is browned, bloomed or layered. That is the gap."""
    fired = _food_rules_fired([SALMON])
    assert "method_is_assembly" in fired
    assert "seasoning_never_mentioned" not in fired, (
        "the salmon does mention salt and lemon — flagging it here would be a "
        "false positive, and a floor that fires on decent dinners is noise"
    )


def test_a_dinner_that_never_mentions_seasoning_is_caught():
    assert "seasoning_never_mentioned" in _food_rules_fired([PINEAPPLE_FREE])


def test_the_good_dinner_stays_clean():
    """The control, and the most important test here.

    A floor that also fires on the dish route 1 holds up as the example of
    doing it right would make the morning report unreadable within a week.
    """
    assert _food_rules_fired([TIKKA]) == set()


@pytest.mark.parametrize("name", [
    # Every one of these fired under the first version of this check, which
    # matched the SHAPE of an absence and nothing else. "Timeless Tiramisu"
    # is the one that settled the argument.
    "No-Knead Bread",
    "No-Bake Cheesecake",
    "Flourless Chocolate Cake",
    "Crustless Quiche Lorraine",
    "Timeless Tiramisu",
    "Effortless Weeknight Chili",
    "Boneless Pork Chops with Apples",
    "Meatless Monday Chili",
])
def test_a_name_that_only_looks_like_an_absence_is_not_flagged(name):
    """The rule is about allergens, not about hyphens.

    Its stated reason is that "a meal named after an allergen is alarming to
    read on the week's menu even when the recipe is safe" — so the absent
    thing has to be something this household actually avoids. Nobody is
    alarmed by "boneless", and nothing in "Timeless" is food at all.
    """
    week = [_dinner("2026-09-07", name, [
        "Sweat the onion.", "Add the rest.", "Simmer 20 minutes with cumin.",
    ])]
    assert "dish_named_for_an_absence" not in _food_rules_fired(week)


def test_the_same_shape_IS_flagged_when_it_names_their_allergen():
    """The other side of the same rule, and the real case: this household has
    "Emily is allergic to pineapple" on record, flagged hard."""
    week = [_dinner("2026-09-07", "Shellfish-Free Paella", [
        "Sweat the onion.", "Add the rest.", "Simmer 20 minutes with saffron.",
    ])]
    assert "dish_named_for_an_absence" in _food_rules_fired(week)


def test_with_nothing_on_record_the_naming_check_stays_silent():
    """A check that cannot tell is a check that should not speak."""
    assert "dish_named_for_an_absence" not in _food_rules_fired(
        [PINEAPPLE_FREE], context={}
    )


@pytest.mark.parametrize("label,steps", [
    ("a dressed salad", [
        "Whisk the lemon juice, mustard and olive oil into a dressing.",
        "Toss the leaves and shaved fennel through it.",
        "Top with toasted hazelnuts and shaved parmesan, and season well.",
    ]),
    ("a cold soba bowl", [
        "Boil the soba until just tender, then rinse under cold water.",
        "Whisk soy, sesame oil, rice vinegar and grated ginger together.",
        "Toss the noodles through with cucumber and scallion.",
    ]),
])
def test_a_dish_that_never_meets_dry_heat_is_not_asked_why_it_did_not_brown(label, steps):
    """These fired under the first version, and the message it gave them —
    "combines and heats" — was false for a dish that applies no heat at all.

    A cold salad is not failing to brown; browning was never on the table. The
    check now needs an oven or a pan in the method before it has anything to
    ask about.
    """
    week = [_dinner("2026-09-07", label.title(), steps)]
    assert "method_is_assembly" not in _food_rules_fired(week)


@pytest.mark.parametrize("entry", [
    _dinner("2026-09-07", "Leftover Chili", ["Reheat.", "Serve."], source="leftovers"),
    _dinner("2026-09-07", "Something Quick", ["Heat it.", "Eat it."]),
    {"date": "2026-09-07", "slot": "breakfast", "state": "planned",
     "meal_name": "Toast", "instructions": ["Toast the bread.", "Butter it.", "Eat."]},
])
def test_the_floor_does_not_judge_what_it_cannot_judge(entry):
    """Leftovers have nothing to season. A two-step method is not evidence
    either way — plenty of good dinners are short, and this is not a length
    rule. Breakfast and lunch are meant to be low-effort; the generation
    prompt says so explicitly, so flagging them would be checking against the
    opposite of the product's own decision."""
    assert _food_rules_fired([entry]) == set()


def test_all_three_are_registered_in_check_week():
    """A check that exists but is never called is the failure mode this
    module's own docstring already records once."""
    week = [PINEAPPLE_FREE, SALMON, TIKKA]
    fired = {v.rule for v in q.check_week(week, AVOIDS)}
    assert FOOD_RULES <= fired | {"method_is_assembly"}
    assert "dish_named_for_an_absence" in fired and "method_is_assembly" in fired


# --------------------------------------------------------------------------
# Being seen — Emily's actual answer
# --------------------------------------------------------------------------

def test_violations_are_persisted_not_just_logged():
    """"Tell you in the morning report" needs a row somewhere. Until
    2026-09-10 check_and_log only wrote to a logger."""
    vs = q.check_week([PINEAPPLE_FREE, SALMON], AVOIDS)
    food = [v for v in vs if v.rule in FOOD_RULES]
    assert food, "fixture should produce something to store"

    tools.record_plan_quality(99, food)
    got = tools.get_recent_plan_quality(days=7)
    assert got["total"] == len(food)
    assert "dish_named_for_an_absence" in got["by_rule"]


def test_food_problems_never_land_under_broken():
    """The report leads with BROKEN, and the whole value of that line is that
    it means exactly one thing: something failed. A dull dinner is a real
    problem and it is not an outage.

    So the food findings print in their own section, and the exit code stays
    0 — exit 1 is the overnight routine's signal to lead with breakage.
    """
    tools.record_plan_quality(99, q.check_week([PINEAPPLE_FREE], AVOIDS))

    import app.db as db
    proc = subprocess.run(
        [sys.executable, "observability_report.py", "--days", "1"],
        cwd=REPO, capture_output=True, text=True,
        env={"PATH": "/usr/bin:/bin", "DB_PATH": db.DB_PATH,
             "HOME_MANAGER_PASSWORD": "test", "SESSION_SECRET": "test",
             "ANTHROPIC_API_KEY": "test", "DISABLE_BACKUPS": "1"},
    )
    out = proc.stdout
    assert "FOOD —" in out, out
    assert "Nothing broke." in out, "a food finding is not an error:\n" + out
    assert proc.returncode == 0, (
        "food findings must not flip the exit code — that is the routine's "
        "signal that something actually broke"
    )
